dependencies: ['repositories.bzl', '*/repositories.bzl', 'third_party/**/*']
documentation: ['docs/**/*']
lang-android: ['android/**/*', 'examples/android/**/*', 'tools/rulegen/android.go']
lang-buf: ['buf/**/*', 'examples/buf/**/*', 'tools/rulegen/buf.go']
lang-c: ['c/**/*', 'examples/c/**/*', 'tools/rulegen/c.go']
lang-cpp: ['cpp/**/*', 'examples/cpp/**/*', 'tools/rulegen/cpp.go']
lang-csharp: ['csharp/**/*', 'examples/csharp/**/*', 'tools/rulegen/csharp.go']
lang-d: ['d/**/*', 'examples/d/**/*', 'tools/rulegen/d.go']
lang-doc: ['doc/**/*', 'examples/doc/**/*', 'tools/rulegen/doc.go']
lang-fsharp: ['fsharp/**/*', 'examples/fsharp/**/*', 'tools/rulegen/fsharp.go']
lang-go: ['go/**/*', 'examples/go/**/*', 'tools/rulegen/go.go']
lang-grpc-gateway: ['grpc-gateway/**/*', 'examples/grpc-gateway/**/*', 'tools/rulegen/grpc_gateway.go']
lang-java: ['java/**/*', 'examples/java/**/*', 'tools/rulegen/java.go']
lang-js: ['js/**/*', 'examples/js/**/*', 'tools/rulegen/js.go', 'tools/rulegen/grpc-web.go']
lang-objc: ['objc/**/*', 'examples/objc/**/*', 'tools/rulegen/objc.go']
lang-php: ['php/**/*', 'examples/php/**/*', 'tools/rulegen/php.go']
lang-python: ['python/**/*', 'examples/python/**/*', 'tools/rulegen/python.go']
lang-ruby: ['ruby/**/*', 'examples/ruby/**/*', 'tools/rulegen/ruby.go']
lang-rust: ['rust/**/*', 'examples/rust/**/*', 'tools/rulegen/rust.go']
lang-scala: ['scala/**/*', 'examples/scala/**/*', 'tools/rulegen/scala.go']
lang-swift: ['swift/**/*', 'examples/swift/**/*', 'tools/rulegen/swift.go']
